[package]
name = "watchmyfile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fanotify-rs = { git = "https://github.com/Percivalll/fanotify-rs.git" }
nix = "0.26.2"
